-- vim: ts=4 sw=4 noet ai cindent syntax=lua
conky.config = {
    alignment = 'bottom_right',
    background = true,
    border_width = 0,
	color0 = '#999999',
	color1 = '#cccccc',
	color2 = '#ff0000',
	color3 = '#005500',
	color4 = '#0000ff',
	color5 = '#ffcc00',
	color6 = '#ccff00',
	color7 = '#0099cc',
	color8 = '#cc6600',
	color9 = '#0061a3',
	diskio_avg_samples = 2,
	double_buffer = true,
    font = 'Hack:size=10',
    gap_x = 1350,
    gap_y = 100,
	minimum_width = 500,
	if_up_strictness = 'link',
    net_avg_samples = 4,
    own_window = true,
	own_window_argb_visual = true,
	own_window_argb_value = 64,
    own_window_type = 'normal',
    own_window_transparent = true,
	--own_window_hints = 'undecorated,sticky,skip_taskbar,skip_pager,below',
    own_window_hints = 'skip_taskbar,skip_pager',
	update_interval = 0.5,
    use_spacer = 'none',
    use_xft = true,
	--update_interval_on_battery = 1,
    --cpu_avg_samples = 2,
	--default_color = 'white',
	--default_bar_height = 6,
	--default_bar_width = 0,
	--default_gauge_height = 25,
	--default_gauge_width = 40,
	--default_graph_height = 25,
	--default_graph_width = ,
    --default_outline_color = 'white',
    --default_shade_color = 'white',
	--disable_auto_reload = true,
	--display = ,
	xinerama_head = 2,
    --draw_borders = false,
    --draw_graph_borders = true,
    --draw_outline = false,
    --draw_shades = false,
    --extra_newline = false,
	--http_refresh = false,
	--max_text_width = 0,
	--max_user_text = 16384,
	--maximum_width = ,
    --minimum_height = 5,
	--minimum_width = ,
    --no_buffers = true,
	--nvidia_display = ,
    --out_to_console = false,
	--out_to_http = false,
	--out_to_ncurses = false,
    --out_to_stderr = false,
	--out_to_x = true,
	--override_utf8_locale = true,
    --own_window_class = 'Conky',
	--own_window_colour = '#000000'
	--own_window_title = 'conky0 (<hostname>)'
	--own_window_transparent = false,
	--short_units = true,
    --show_graph_scale = false,
    --show_graph_range = false,
    --stippled_borders = 0,
	--text_buffer_size = 256,
	--top_cpu_separate = true,
	--top_name_verbose = true,
	--top_name_width = 15,
	--total_run_times = 0,
}
conky.text = [[
${color #ffff00}GPU: \
${goto 50}${nvidia gpuutil}%\
${goto 90}${nvidia gpufreqcur}mHz\
${goto 180}${color #ff3300}${nvidia gputemp}C\
${goto 260}${color #00ff00}MEM: ${nvidia memutil}% Used:${nvidia memused}MB Free:${nvidia memmax}MB
${color #88cc00}${nvidiagraph gpuutil 25,250 ff0000 00ff00} \
${color #88cc00}${nvidiagraph memutil 25,250 ff0000 00ff00}
$hr
]]
